/**
 * QR adapter seam.
 *
 * QR codes are generated by the Art QR API, which requires a secret `ApiKey`
 * header. The browser must never hold that key — anything in a `VITE_*` variable
 * is inlined into the client bundle — so the app calls the server-side proxy
 * (`server/qr-proxy.mjs`) at `/api/qr`, and the proxy attaches the key.
 *
 * Two things were established against the live API on 2026-09-10 and both are
 * load-bearing:
 *
 *  1. The request must carry the COMPLETE InputParameters body. A partial body
 *     (even `{"inputText": "..."}`, or one missing the premium colour fields)
 *     makes the provider answer a bare 500 — no Content-Type, zero bytes. The
 *     defaults below are copied from a payload that returns 200; do not trim
 *     them without re-running `npm run qr:verify`.
 *  2. A successful response is RAW PNG BYTES (`content-type: image/png`), not
 *     JSON, despite the Swagger declaring `produces: application/json` and no
 *     200 schema. `parseQrResponse()` therefore turns the bytes into a `blob:`
 *     URL — which QrDisplay revokes when it unmounts.
 *
 * `qrUrl()` keeps its async "resolve to an <img>-usable src" contract.
 */

export interface QrRequest {
  url: string;
  init: RequestInit;
}

const DEFAULT_PROXY_PATH = '/api/qr';

const EXPORT_WIDTH = 1000;
const ECC_LEVEL = 'H';
const SHAPE_NAME = 'One';

/**
 * The provider throws on partial nested objects, so these mirror the verified
 * working payload field for field.
 */
const COLOR_PARAMETERS = {
  premiumFiveFirst: '000000',
  premiumFiveSecond: 'ff0000',
  premiumFourFirst: '000000',
  premiumFourSecond: 'ff0000',
  premiumThreeFirst: '000000',
  premiumThreeSecond: 'ff0000',
  premiumTwoFirst: '000000',
  premiumTwoSecond: 'ff0000',
  premiumTwoTwoFirst: '000000',
  premiumTwoTwoSecond: 'ff0000',
  premiumCrossFirst: '000000',
  premiumCrossSecond: 'ff0000',
  premiumCrossThird: '555555',
  premiumCrossFourth: '888888',
  first: '000000',
  second: 'ff0000',
  third: '555555',
  fourth: '888888',
  background: 'ffffff',
  useRandomColors: false,
};

const EYE_PARAMETERS = {
  eyeFrameType: 'Square',
  eyeBallType: 'Circle',
  eyeFrameColorMarker: 'ff0000',
  eyeFrameColorTopRight: 'ff0000',
  eyeFrameColorLeftBottom: 'ff0000',
  eyeBallColorMarker: '000000',
  eyeBallColorTopRight: '000000',
  eyeBallColorLeftBottom: '000000',
  randomEyeFrame: false,
};

const GRADIENT_PARAMETERS = {
  linearGradient: false,
  radialGradient: false,
  eyeGradient: false,
  gradientColorFirstHex: 'ff0000',
  gradientColorSecondHex: '000000',
};

const LOGO_PARAMETERS = {
  logoName: 'empty',
  logoVariation: 'Normal',
  logoBackgroundColorHexFormat: '',
  logoRemoveBackground: true,
  logoFile: '',
};

const PREMIUM_PARAMETERS = {
  five: true,
  four: true,
  three: true,
  two: true,
  twoTwo: true,
  cross: true,
  horizontal: true,
  vertical: true,
};

/**
 * Proxy endpoint. Defaults to the same-origin path `/api/qr`, which is what
 * both the Vite dev server and a production reverse proxy should expose; set
 * `VITE_QR_PROXY_URL` only when the proxy lives on another origin.
 *
 * Throws on a malformed value rather than passing it to `fetch`: a typo would
 * otherwise send card links to whatever host the string happens to name.
 */
export function qrApiUrl(): string {
  const configured = import.meta.env.VITE_QR_PROXY_URL?.trim();
  if (!configured) return DEFAULT_PROXY_PATH;

  const cleaned = configured.replace(/\/+$/, '');
  if (cleaned.startsWith('/')) return cleaned;
  if (/^https?:\/\//i.test(cleaned)) return cleaned;
  throw new Error(
    `VITE_QR_PROXY_URL must be an absolute http(s) URL or a same-origin path starting with "/" (got "${configured}").`,
  );
}

/**
 * Builds the POST request. Pure, so tests can assert it without a network.
 *
 * No authorization header is ever set here: the API key belongs to the proxy and
 * must not be reachable from the bundle. `src/lib/qr.test.ts` locks that in, and
 * also locks the completeness of the body — see the module header.
 */
export function qrRequest(data: string): QrRequest {
  return {
    url: qrApiUrl(),
    init: {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        colorParameters: COLOR_PARAMETERS,
        eyeParameters: EYE_PARAMETERS,
        gradientParameters: GRADIENT_PARAMETERS,
        logoParameters: LOGO_PARAMETERS,
        premiumParameters: PREMIUM_PARAMETERS,
        inputText: data,
        exportWidth: EXPORT_WIDTH,
        exportPNG: true,
        eccLevel: ECC_LEVEL,
        shapeName: SHAPE_NAME,
      }),
    },
  };
}

/** Sends the request. Kept separate from qrRequest so both stay testable. */
export async function requestQr(data: string): Promise<Response> {
  const { url, init } = qrRequest(data);
  return fetch(url, init);
}

/**
 * Turns a successful response into an `<img>`-usable src.
 *
 * The provider returns raw PNG bytes, so this hands back a `blob:` URL. Callers
 * that keep the URL (QrDisplay) must revoke it when they are done with it.
 */
export async function parseQrResponse(res: Response): Promise<string> {
  const contentType = res.headers.get('content-type') ?? '';
  const blob = await res.blob();

  // A 200 carrying the SPA shell means no /api/qr route answered the call (or
  // the service worker served index.html). Say that instead of reporting a
  // shape problem, so the failure points at the deployment, not the parser.
  if (contentType.includes('text/html')) {
    throw new Error(
      `QR proxy returned HTML (content-type "${contentType}") instead of a QR: no route handled ${qrApiUrl()}. Deploy server/qr-proxy.mjs behind that path, or point VITE_QR_PROXY_URL at the proxy.`,
    );
  }

  if (!contentType.startsWith('image/') || blob.size === 0) {
    throw new Error(
      `QR proxy returned ${res.status} with content-type "${contentType || '(none)'}" and ${blob.size} bytes; expected raw image bytes (the provider answers image/png for a complete InputParameters body — run npm run qr:verify).`,
    );
  }

  return URL.createObjectURL(blob);
}

/** Stable async contract: always resolves to an <img>-usable src. */
export async function qrUrl(data: string): Promise<string> {
  const res = await requestQr(data);
  if (!res.ok) {
    const detail = await res.text().catch(() => '');
    throw new Error(`QR API request failed: HTTP ${res.status}${detail ? ` — ${detail.slice(0, 200)}` : ' (empty body)'}`);
  }
  return parseQrResponse(res);
}

export async function downloadQr(data: string, filename: string): Promise<void> {
  const src = await qrUrl(data);
  const a = document.createElement('a');
  // Both `blob:` and `data:` URLs work as an href with the download attribute,
  // so point at it directly: re-fetching and re-wrapping in a second object URL
  // would retain the PNG bytes in the blob store for the page's lifetime.
  a.href = src;
  a.download = filename;
  a.click();
  if (src.startsWith('blob:')) setTimeout(() => URL.revokeObjectURL(src), 1000);
}
