/**
 * QR adapter seam.
 *
 * QR codes are generated by the Art QR API, which requires a secret `ApiKey`
 * header. The browser must never hold that key — anything in a `VITE_*` variable
 * is inlined into the client bundle and readable by every visitor — so the app
 * calls the server-side proxy (`server/qr-proxy.mjs`) at `/api/qr`, and the
 * proxy attaches the key on the way out. In development Vite forwards that
 * same-origin path to the local proxy, so no CORS is involved either.
 *
 * Response parsing is deliberately NOT implemented. As of 2026-09-10 the
 * provider answers every authenticated request with a bare 500 — no
 * Content-Type, zero bytes — so its success shape (raw PNG, JSON carrying
 * base64, or a URL?) has never been observed. `parseQrResponse()` is the single
 * place that will do it, and until then it throws with the observed evidence
 * rather than encoding a guess. `npm run qr:verify` prints the shape the moment
 * the provider returns a 200.
 *
 * `qrUrl()` keeps its async "resolve to an <img>-usable src" contract, so
 * QrDisplay and PanelPage need no changes when parsing lands.
 */

export interface QrRequest {
  url: string;
  init: RequestInit;
}

const ECC_LEVEL = 'M';
const EXPORT_WIDTH = 512;
const DEFAULT_PROXY_PATH = '/api/qr';

/**
 * Proxy endpoint. Defaults to the same-origin path `/api/qr`, which is what
 * both the Vite dev server and a production reverse proxy should expose; set
 * `VITE_QR_PROXY_URL` only when the proxy lives on another origin.
 *
 * Throws on a malformed value rather than passing it to `fetch`: a typo would
 * otherwise send card links to whatever host the string happens to name.
 */
export function qrApiUrl(): string {
  const configured = import.meta.env.VITE_QR_PROXY_URL?.trim();
  if (!configured) return DEFAULT_PROXY_PATH;

  const cleaned = configured.replace(/\/+$/, '');
  if (cleaned.startsWith('/')) return cleaned;
  if (/^https?:\/\//i.test(cleaned)) return cleaned;
  throw new Error(
    `VITE_QR_PROXY_URL must be an absolute http(s) URL or a same-origin path starting with "/" (got "${configured}").`,
  );
}

/**
 * Builds the POST request. Pure, so tests can assert it without a network.
 *
 * No authorization header is ever set here: the API key belongs to the proxy and
 * must not be reachable from the bundle. `src/lib/qr.test.ts` locks that in.
 */
export function qrRequest(data: string): QrRequest {
  return {
    url: qrApiUrl(),
    init: {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ inputText: data, exportWidth: EXPORT_WIDTH, exportPNG: true, eccLevel: ECC_LEVEL }),
    },
  };
}

/** Sends the request. Kept separate from qrRequest so both stay testable. */
export async function requestQr(data: string): Promise<Response> {
  const { url, init } = qrRequest(data);
  return fetch(url, init);
}

/**
 * Turns a successful response into an `<img>`-usable src.
 *
 * NOT IMPLEMENTED ON PURPOSE — see the module header. Implement it from a real
 * 200 response, never from a guess: run `npm run qr:verify`, then parse the
 * shape it reports.
 */
export async function parseQrResponse(res: Response): Promise<string> {
  const bytes = new Uint8Array(await res.arrayBuffer());
  const contentType = res.headers.get('content-type') ?? '(none)';

  // A 200 carrying the SPA shell means no /api/qr route answered the call (or
  // the service worker served index.html). Say that instead of reporting a
  // shape problem, so the failure points at the deployment, not the parser.
  if (contentType.includes('text/html')) {
    throw new Error(
      `QR proxy returned HTML (content-type "${contentType}") instead of a QR: no route handled ${qrApiUrl()}. Deploy server/qr-proxy.mjs behind that path, or point VITE_QR_PROXY_URL at the proxy.`,
    );
  }

  throw new Error(
    `QR API returned 200 with ${bytes.length} bytes and content-type "${contentType}", but response parsing is not implemented yet — run npm run qr:verify and implement it against the reported shape.`,
  );
}

/** Stable async contract: always resolves to an <img>-usable src. */
export async function qrUrl(data: string): Promise<string> {
  const res = await requestQr(data);
  if (!res.ok) {
    const detail = await res.text().catch(() => '');
    throw new Error(`QR API request failed: HTTP ${res.status}${detail ? ` — ${detail.slice(0, 200)}` : ' (empty body)'}`);
  }
  return parseQrResponse(res);
}

export async function downloadQr(data: string, filename: string): Promise<void> {
  const src = await qrUrl(data);
  const a = document.createElement('a');
  if (src.startsWith('data:')) {
    a.href = src;
  } else {
    const blob = await (await fetch(src)).blob();
    a.href = URL.createObjectURL(blob);
  }
  a.download = filename;
  a.click();
  if (a.href.startsWith('blob:')) setTimeout(() => URL.revokeObjectURL(a.href), 1000);
}
