/**
 * QR adapter seam.
 *
 * QR codes are generated by an external HTTP API configured with
 * `VITE_QR_API_URL`: the API is called with GET, receives the target link as a
 * query parameter, and returns image bytes. The resulting URL is therefore used
 * directly as an `<img>` src — no local QR rendering happens in the browser.
 *
 * `qrUrl` stays async on purpose. Its contract is "resolve to an <img>-usable
 * src"; keeping it a Promise means an API that later needs POST + JSON can
 * fetch the bytes here and return a `blob:` URL without any consumer changing.
 */

/**
 * Builds the QR API URL for `data`.
 *
 * Two supported endpoint shapes:
 *  - a `{data}` placeholder anywhere in the URL, e.g.
 *    `https://qr.example.com/make?text={data}&format=png`
 *  - a plain base URL, in which case `data=<encoded>` is appended, e.g.
 *    `https://qr.example.com/gen` -> `.../gen?data=https%3A%2F%2Fhost%2Fc%2Fabc`
 *
 * Throws when `VITE_QR_API_URL` is unset: a missing endpoint is a configuration
 * error, and failing loudly beats rendering a blank QR area.
 */
export function externalQrUrl(data: string): string {
  const template = import.meta.env.VITE_QR_API_URL?.trim();
  if (!template) {
    throw new Error('VITE_QR_API_URL is not configured (QR generation API endpoint).');
  }
  if (template.includes('{data}')) return template.replace('{data}', encodeURIComponent(data));
  return `${template}${template.includes('?') ? '&' : '?'}data=${encodeURIComponent(data)}`;
}

/** Stable async contract: always resolves to an <img>-usable src. */
export async function qrUrl(data: string): Promise<string> {
  return externalQrUrl(data);
}

export async function downloadQr(data: string, filename: string): Promise<void> {
  const src = await qrUrl(data);
  const a = document.createElement('a');
  if (src.startsWith('data:')) {
    a.href = src;
  } else {
    const blob = await (await fetch(src)).blob();
    a.href = URL.createObjectURL(blob);
  }
  a.download = filename;
  a.click();
  if (a.href.startsWith('blob:')) setTimeout(() => URL.revokeObjectURL(a.href), 1000);
}
